services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - bigdata_net

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - bigdata_net

  superset:
    image: apache/superset
    environment:
      SUPERSET_SECRET_KEY: 'some-secret-key'
      SUPERSET_SQLALCHEMY_DATABASE_URI: 'sqlite:////var/lib/superset/superset.db'
    ports:
      - "8088:8088"
    volumes:
      - ./superset:/app/superset_home
    networks:
      - bigdata_net

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - bigdata_net

  # spark-master:
  #   build:
  #     context: ./docker_image
  #     dockerfile: ./Dockerfile
  #   container_name: "spark-master"
  #   ports:
  #     - "7077:7077"  # Spark master port
  #     - "8081:8080"  # Spark master web UI port
  #   expose: 
  #     - "7077"
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #     - SPARK_USER=spark
  #   volumes:
  #     - ./docker_image/spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
  #     - ./docker_image/spark/conf/log4j.properties:/opt/bitnami/spark/conf/log4j.properties
  #     - ./data:/opt/spark
  #   networks:
  #     - bigdata_net

  # spark-worker-1:
  #   image: docker.io/bitnami/spark:3.3.2
  #   container_name: "spark-worker-1"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - spark-master
  #   networks:
  #     - bigdata_net

networks:
  bigdata_net:
    driver: bridge
